REMOVE @PG13WARETEST_STAGE/pgsdeprod_prod_wld.glj_wld_well_bh.csv;
REMOVE @PG13WARETEST_STAGE/pgsdeprod_prod_can.glj_well_dir_srvy_loc.csv;
REMOVE @PG13WARETEST_STAGE/pgsdeprod_prod_can.geobase_aboriginal_lands.csv;
